destination: public
exclude: [Gemfile, Gemfile.lock, .ruby-*, public]

gmaps_api_key: AIzaSyDy6XphVua57uoLzT_1F3KhvkfWIUqdqYg
title: "Anchorage, AK: Get A Flu Shot"
logo: "img/logo.png"
locality: "Anchorage, Alaska"
flu_info_link: http://vaccinefinder.org/
start_latitude: 61.196287
start_longitude: -149.904251
state: Alaska
api_endpoint: http://brigades.opendatanetwork.com/resource/7mef-4h72.json
socrata_app_token: 46C5V5L2v9fouMtYZu2ZlJZ9y
about:
  Developed orginally by [Tom Kompare](http://about.me/tomkompare) in partnership with the [NC Department of Public Health (CDPH)](http://www.cityofchicago.org/city/en/depts/cdph.html). This map application is developed in partnership with [Code for Raleigh](http://www.codeforraleigh.com) and Socrata. 

  [The code behind this web application](https://github.com/socrata/flushots) is free, open, and under a [MIT License](https://github.com/socrata/flushots/blob/master/LICENSE). The data behind the application is a [ Socrata dataset](https://brigades.opendatanetwork.com/HEALTH/North-Carolina-Flu-Shot-Locations/7mef-4h72) hosted on the [Brigade Open Data Sharing Platform.](https://brigades.opendatanetwork.com/)

